services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    KooijmanInc\Suzie\Model\Connection\ConnectionFactory:
        class: KooijmanInc\Suzie\Model\Connection\ConnectionFactory
        public: true