services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    KooijmanInc\Suzie\:
        resource: '%kernel.project_dir%/vendor/baskooijmaninc/suzie/src/*'